# ESTADOS DE LICITACIÓN (CodigoEstado)
EST_LICITACION_PUBLICADA=5
EST_LICITACION_CERRADA=6
EST_LICITACION_DESIERTA=7
EST_LICITACION_ADJUDICADA=8
EST_LICITACION_REVOCADA=18
EST_LICITACION_SUSPENDIDA=19
EST_LICITACION_TODOS=todos

# TIPOS DE LICITACIÓN (CodigoTipo)
TIPO_LICITACION_L1=L1
TIPO_LICITACION_LE=LE
TIPO_LICITACION_LP=LP
TIPO_LICITACION_LS=LS
TIPO_LICITACION_A1=A1
TIPO_LICITACION_B1=B1
TIPO_LICITACION_E1=E1
TIPO_LICITACION_D1=D1
TIPO_LICITACION_C1=C1
TIPO_LICITACION_F1=F1
TIPO_LICITACION_G1=G1

# MONEDAS (Moneda)
MONEDA_PESO_CHILENO=CLP
MONEDA_DOLAR_USA=USD
MONEDA_UNIDAD_FOMENTO=CLF
MONEDA_UTM=UTM

# CONFIGURACIÓN API
CHILECOMPRA_API_BASE_URL=https://api.mercadopublico.cl/servicios/v1/publico/
CHILECOMPRA_API_DATE_FORMAT=ddmmaaaa



#{estados} de las licitaciones
#Publicada
#Cerrada
#Desierta
#Adjudicada
#Revocada
#Suspendida