# Configuración de API Mercado Público
API_LICITACION_URL=https://api.mercadopublico.cl/servicios/v1/publico/licitaciones.json
API_ORDENESDECOMPRA_URL=https://api.mercadopublico.cl/servicios/v1/publico/ordenesdecompra.json
API_BUSQUEDA_PROVEEDOR_URL =https://api.mercadopublico.cl/servicios/v1/Publico/Empresas/BuscarProveedor
API_BUSCAR_COMPRADOR_URL= https://api.mercadopublico.cl/servicios/v1/Publico/Empresas/BuscarComprador
TICKET=F8537A18-6766-4DEF-9E59-426B4FEE2844
